// ==UserScript==
// @name          SpookyX
// @description   Enhances functionality of FoolFuuka boards. Developed further for more comfortable ghost-posting on the moe archives.
// @author        Fiddlekins
// @version       32.50
// @namespace     https://github.com/Fiddlekins/SpookyX
// @include       http://archive.4plebs.org/*
// @include       https://archive.4plebs.org/*
// @include       http://archive.loveisover.me/*
// @include       https://archive.loveisover.me/*
// @include       http://archive.nyafuu.org/*
// @include       https://archive.nyafuu.org/*
// @include       http://desuarchive.org/*
// @include       https://desuarchive.org/*
// @include       http://cuckchan.org/*
// @include       https://cuckchan.org/*
// @include       http://4ch.be/*
// @include       https://4ch.be/*
// @include       http://arch.b4k.co/*
// @include       https://arch.b4k.co/*
// @include       http://*ch.archive.horse*
// @include       https://*ch.archive.horse*
// @include       http://boards.fireden.net/*
// @include       https://boards.fireden.net/*
// @include       http://archived.moe/*
// @include       https://archived.moe/*
// @include       http://archiveofsins.com/*
// @include       https://archiveofsins.com/*
// @include       http://thebarchive.com/*
// @include       https://thebarchive.com/*
// @include       http://archive.whatisthisimnotgoodwithcomputers.com/*
// @include       https://archive.whatisthisimnotgoodwithcomputers.com/*
// @include       http://magyarchan.net/*
// @include       https://magyarchan.net/*
// @include       http://www.tokyochronos.net/*
// @include       https://www.tokyochronos.net/*
// @require       https://cdn.rawgit.com/madapaja/jquery.selection/master/src/jquery.selection.js
// @require       https://raw.githubusercontent.com/jquery/jquery-mousewheel/master/jquery.mousewheel.min.js
// @require       https://raw.githubusercontent.com/carloscabo/colz/master/public/js/colz.class.min.js
// @grant         none
// @updateURL     https://github.com/Fiddlekins/SpookyX/raw/master/SpookyX.meta.js
// @downloadURL   https://github.com/Fiddlekins/SpookyX/raw/master/SpookyX.user.js
// @icon          https://i.imgur.com/LaYyYRl.png
// ==/UserScript==
